{{- include "stackstate-k8s-agent.customCertificates.validate" . }}
{{- if and .Values.global.customCertificates.enabled .Values.global.customCertificates.pemData (not .Values.global.customCertificates.configMapName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stackstate-k8s-agent.customCertificates.configmap.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: custom-certificates
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
data:
  tls.pem: |
{{ .Values.global.customCertificates.pemData | indent 4 }}
{{- end }}
