{{- if include "stackstate-k8s-agent.processAgent.podCorrelation.remoteCache.enabled" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-remote-kube-cache
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: remote-kube-cache
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
{{- end }}
