apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackstate-k8s-agent.secret.internal.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
type: Opaque
data:
{{- if .Values.global.receiverApiKey }}
  STS_API_KEY: {{ .Values.global.receiverApiKey | b64enc | quote }}
{{- else if .Values.stackstate.apiKey }}
  STS_API_KEY: {{ .Values.stackstate.apiKey | b64enc | quote }}
{{- else if not .Values.stackstate.manageOwnSecrets }}
  {{- if eq .Values.global.apiKey.fromSecret "{{ include \"stackstate-k8s-agent.secret.internal.name\" . }}" }}
    {{- fail "Please provide an api key." -}}
  {{- end }}
{{- end }}
{{- if .Values.stackstate.cluster.authToken }}
  STS_CLUSTER_AGENT_AUTH_TOKEN: {{ .Values.stackstate.cluster.authToken | b64enc | quote }}
{{- else }}
  STS_CLUSTER_AGENT_AUTH_TOKEN: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
{{- range $key, $value := .Values.global.extraEnv.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
