# This is always ran to allow for the delete job to be ran.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "http-header-injector.cert-serviceaccount.name" . }}"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,post-install,pre-upgrade,post-upgrade,post-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{ include "http-header-injector.global.extraAnnotations" . | indent 4 }}
  labels:
    app.kubernetes.io/component: http-header-injector-cert-hook
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "http-header-injector.app.name" . }}
    app: "{{ include "http-header-injector.app.name" . }}"
{{ include "http-header-injector.global.extraLabels" . | indent 4 }}
