{{- $defaultRegistry := .Values.global.imageRegistry }}
{{- $top := . }}
{{- $registryAuthMap := dict }}

{{- range $registry, $credentials := .Values.global.imagePullCredentials }}
  {{- $registryAuthDocument := dict -}}
  {{- $_ := set $registryAuthDocument "username" $credentials.username }}
  {{- $_ := set $registryAuthDocument "password" $credentials.password }}
  {{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
  {{- $_ := set $registryAuthDocument "auth" $authMessage }}
  {{- if eq $registry "default" }}
    {{- $registryAuthMap := set $registryAuthMap (include "kubernetes-rbac-agent.image.registry.global" $top) $registryAuthDocument }}
  {{ else }}
    {{- $registryAuthMap := set $registryAuthMap $registry $registryAuthDocument }}
  {{- end }}
{{- end }}
{{- $dockerAuthsDocuments := dict "auths" $registryAuthMap }}

apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-rbac-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "kubernetes-rbac-agent.app.name" . }}
    {{- include "kubernetes-rbac-agent.global.commonLabels" . | indent 4 }}
  annotations:
    {{- include "kubernetes-rbac-agent.global.commonAnnotations" . | indent 4 }}
  name: {{ include "kubernetes-rbac-agent.pull-secret.name" .  }}
data:
  .dockerconfigjson: {{ $dockerAuthsDocuments | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
