{{- if include "stackstate-k8s-agent.processAgent.podCorrelation.remoteCache.enabled" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stackstate-k8s-agent.remoteKubeCache.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: remote-kube-cache
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: remote-kube-cache
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "stackstate-k8s-agent.name" . }}
  ports:
    - name: grpc
      port: {{ include "stackstate-k8s-agent.remoteKubeCache.grpcPort" . }}
      protocol: TCP
    - name: internalprom
      port: 8999
      protocol: TCP
{{- end }}
