{{- define "kubernetes-rbac-agent.api-key.secret.internal" -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-rbac-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "kubernetes-rbac-agent.app.name" . }}
    {{- include "kubernetes-rbac-agent.global.commonLabels" . | indent 4 }}
  annotations:
    {{- include "kubernetes-rbac-agent.global.commonAnnotations" . | indent 4 }}
  name: {{ template "kubernetes-rbac-agent.api-key.secret.internal.name" . }}
data:
  STS_API_KEY: {{ tpl .Values.apiKey . | b64enc | quote }}
{{- end -}}

{{- if .Values.apiKey }}
{{- $stackstateApiKeyInternalSecret := fromYaml (include "kubernetes-rbac-agent.api-key.secret.internal" .) -}}
{{- toYaml (merge $stackstateApiKeyInternalSecret) -}}
{{- end }}