apiVersion: v1
appVersion: 1.5.2
description: A Helm chart for the ACK service controller for AWS Identity & Access
  Management (IAM)
home: https://github.com/aws-controllers-k8s/iam-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
keywords:
- aws
- kubernetes
- iam
maintainers:
- name: ACK Admins
  url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
- name: IAM Admins
  url: https://github.com/orgs/aws-controllers-k8s/teams/iam-maintainer
name: iam-chart
sources:
- https://github.com/aws-controllers-k8s/iam-controller
version: 1.5.201+up1.5.2
